name: Install Server
description: Install the server
runs:
  using: "composite"
  
  steps:      
    - name: Start MongoDB
      uses: ankane/setup-mongodb@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: "npm"
        cache-dependency-path: './backend/package-lock.json'
    - name: Install Dependencies
      working-directory: ./backend
      shell: bash
      run: npm install