name: Install Server
description: Install the server
runs:
  using: "composite"
  
  steps:      
    - run: docker-compose --env-file ./tools/docker/compose_prod.env -f ./tools/docker/docker-compose.yml up  --detach
      shell: bash
      env:
        FLUTTER_WORKSPACE_DIRECTORY: ${{ github.workspace }}
        CREDENTIALS_FOLDER: ${{ github.workspace }}/fake_credentials
    