// Mocks generated by Mockito 5.2.0 from annotations
// in avecpaulette/test/features/credentials/domain/usecases/login_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:avecpaulette/features/credentials/domain/entities/user.dart'
    as _i4;
import 'package:avecpaulette/features/credentials/domain/repositories/credentials_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [CredentialsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCredentialsRepository extends _i1.Mock
    implements _i2.CredentialsRepository {
  MockCredentialsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.User> login(String? mail, String? password) =>
      (super.noSuchMethod(Invocation.method(#login, [mail, password]),
          returnValue: Stream<_i4.User>.empty()) as _i3.Stream<_i4.User>);
  @override
  _i3.Stream<_i4.User> signup(String? mail, String? password) =>
      (super.noSuchMethod(Invocation.method(#signup, [mail, password]),
          returnValue: Stream<_i4.User>.empty()) as _i3.Stream<_i4.User>);
}
