version: '3'
services:
  node:
    image: nicolas71640/node_server 
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ${FLUTTER_WORKSPACE_DIRECTORY}/backend:/root/backendWorkspace
    environment:
      - FLUTTER_BACKEND_WORKSPACE_DIRECTORY=/root/backendWorkspace
      - FLUTTER_WORKSPACE_DIRECTORY=/root
      - CREDENTIALS_FOLDER=/root/credentials
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ${FLUTTER_WORKSPACE_DIRECTORY}/frontend/assets:/docker-entrypoint-initdb.d/assets

    environment:
      - MONGO_URL=mongodb://mongo:27017/myapp
      - INITIAL_JSON=/root/assets/cottages.json

volumes:
 mongodb: