version: '3'
services:
  node:
    image: nicolas71640/node_server 
    container_name: server 
    restart: always
    depends_on:  
      - mongo
    networks:
      - serverAndDb
    ports:
      - 3000:3000
    volumes:
      - ${FLUTTER_WORKSPACE_DIRECTORY}/backend:/root/backendWorkspace
    environment:
      - FLUTTER_BACKEND_WORKSPACE_DIRECTORY=${BACKEND_SOURCE}
      - CREDENTIALS_FOLDER=/root/credentials
      - MONGO_URL=mongodb://mongo:27017/myapp
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - serverAndDb
    volumes:
      - mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ${FLUTTER_WORKSPACE_DIRECTORY}/frontend/assets:/docker-entrypoint-initdb.d/assets

    environment:
      - MONGO_URL=mongodb://mongo:27017/myapp
      - INITIAL_JSON=/root/assets/cottages.json

volumes:
 mongodb:

networks:
  serverAndDb:
    driver: bridge